---
- hosts: all
  become: true
  gather_facts: true
  roles:
    - update
    - prereq
- hosts: master
  become: true
  roles: 
    - master
- hosts: master-ha
  become: true
  roles:
    - ha
- hosts: nodes
  become: true
  roles: 
    - nodes
- hosts: localhost
  roles:
    - helm
