---
- hosts: milkyway
  become: true
  gather_facts: true
  vars:
    node_token: null
  tasks:
    - name: Update System
      apt:
        name: "*"
        state: latest

    - name: Full Upgrade System
      apt:
        upgrade: "full"

    - name: Install IPTABLES
      apt:
        name: "iptables"
        state: latest

    - name: Change IPTABLES
      shell: "{{ item }}"
      args: 
        executable: /bin/sh
      loop:
        - sudo iptables -F
        - sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
        - sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

    - name: Add CGROUPS
      copy:
        src: ./files/cmdline.txt
        dest: /boot/cmdline.txt.bak
    - name: Reboot machine
      reboot:
        reboot_timeout: 300

- hosts: k3s-master
  become: true
  gather_facts: false
  tasks:
    - name: Install K3S
      shell: curl -sfL https://get.k3s.io | sh -s - --disable servicelb
    - name: get NODE_TOKEN
      slurp:
        path: /var/lib/rancher/k3s/server/node-token
      register: node_token
