---
- name: validate container feature in cmdline
  command: grep --extended-regexp --ignore-case "cgroup_memory=1 cgroup_enable=memory$" /boot/cmdline.txt
  register: cmdlinecheck
  ignore_errors: yes

- name: Change cmdline.txt
  when: cmdlinecheck.rc == 1
  notify: 
    - 'Reboot'
  ansible.builtin.replace:
    path: /boot/cmdline.txt
    regexp: 'rootwait'
    replace: 'rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
